In [4]:
import tensorflow as tf

In [5]:
x = tf.ones(shape=(2,1))
print(x)

tf.Tensor(
[[1.]
 [1.]], shape=(2, 1), dtype=float32)


In [7]:
tf.zeros(shape=(2,1))

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[0.],
       [0.]], dtype=float32)>

In [11]:
x=tf.random.normal(shape=(3,1),mean=0., stddev=1.)
print(x)

tf.Tensor(
[[-2.0075924 ]
 [-0.6683617 ]
 [ 0.39777112]], shape=(3, 1), dtype=float32)


In [13]:
import numpy as np

In [16]:
x=np.ones(shape=(2,2))
print(x)

[[1. 1.]
 [1. 1.]]


In [17]:
v= tf.Variable(initial_value=tf.random.normal(shape=(3,1)))
print(v)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[ 0.5145176],
       [-1.6416825],
       [ 1.0631835]], dtype=float32)>


In [18]:
v.assign(tf.ones(shape=(3,1)))

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[1.],
       [1.],
       [1.]], dtype=float32)>

In [19]:
v[0,0].assign(3)

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[3.],
       [1.],
       [1.]], dtype=float32)>

In [20]:
v.assign_add(tf.ones((3,1)))

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[4.],
       [2.],
       [2.]], dtype=float32)>

In [22]:
b= tf.square(v)
print(b)

tf.Tensor(
[[16.]
 [ 4.]
 [ 4.]], shape=(3, 1), dtype=float32)


In [25]:
input_var = tf.Variable(initial_value=3)
print(input_var)
with tf.GradientTape() as tape:
    tape.watch(input_var)
    result = tf.square(input_var)
gradient = tape.gradient(result, input_var)
print(gradient)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=3>
None
